/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DocChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "getCertStatus"
      | "getVerifyCount"
      | "grantIssuer"
      | "issuers"
      | "revokeDocument"
      | "revokeIssuer"
      | "storeDocument"
      | "transferAdmin"
      | "verifyDocument"
      | "verifyDocumentView"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DocumentRevoked"
      | "DocumentStored"
      | "DocumentVerified"
      | "IssuerGranted"
      | "IssuerRevoked"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCertStatus",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifyCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "grantIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issuers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDocument",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storeDocument",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDocument",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDocumentView",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCertStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerifyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "issuers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDocumentView",
    data: BytesLike
  ): Result;
}

export namespace DocumentRevokedEvent {
  export type InputTuple = [
    hashKey: string,
    revokedBy: AddressLike,
    revokedAt: BigNumberish
  ];
  export type OutputTuple = [
    hashKey: string,
    revokedBy: string,
    revokedAt: bigint
  ];
  export interface OutputObject {
    hashKey: string;
    revokedBy: string;
    revokedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DocumentStoredEvent {
  export type InputTuple = [
    hashKey: string,
    issuedBy: AddressLike,
    ipfsCID: string,
    docType: string,
    issuedAt: BigNumberish
  ];
  export type OutputTuple = [
    hashKey: string,
    issuedBy: string,
    ipfsCID: string,
    docType: string,
    issuedAt: bigint
  ];
  export interface OutputObject {
    hashKey: string;
    issuedBy: string;
    ipfsCID: string;
    docType: string;
    issuedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DocumentVerifiedEvent {
  export type InputTuple = [
    hashKey: string,
    verifiedBy: AddressLike,
    status: BigNumberish,
    verifiedAt: BigNumberish
  ];
  export type OutputTuple = [
    hashKey: string,
    verifiedBy: string,
    status: bigint,
    verifiedAt: bigint
  ];
  export interface OutputObject {
    hashKey: string;
    verifiedBy: string;
    status: bigint;
    verifiedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerGrantedEvent {
  export type InputTuple = [issuer: AddressLike, grantedBy: AddressLike];
  export type OutputTuple = [issuer: string, grantedBy: string];
  export interface OutputObject {
    issuer: string;
    grantedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerRevokedEvent {
  export type InputTuple = [issuer: AddressLike, revokedBy: AddressLike];
  export type OutputTuple = [issuer: string, revokedBy: string];
  export interface OutputObject {
    issuer: string;
    revokedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DocChain extends BaseContract {
  connect(runner?: ContractRunner | null): DocChain;
  waitForDeployment(): Promise<this>;

  interface: DocChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  getCertStatus: TypedContractMethod<[_hash: string], [bigint], "view">;

  getVerifyCount: TypedContractMethod<[_hash: string], [bigint], "view">;

  grantIssuer: TypedContractMethod<
    [_issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  issuers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  revokeDocument: TypedContractMethod<[_hash: string], [void], "nonpayable">;

  revokeIssuer: TypedContractMethod<
    [_issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  storeDocument: TypedContractMethod<
    [_hash: string, _ipfsCID: string, _docType: string],
    [void],
    "nonpayable"
  >;

  transferAdmin: TypedContractMethod<
    [_newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyDocument: TypedContractMethod<
    [_hash: string],
    [
      [bigint, string, bigint, bigint, string, string, bigint] & {
        status: bigint;
        issuedBy: string;
        issuedAt: bigint;
        revokedAt: bigint;
        ipfsCID: string;
        docType: string;
        verifyCount: bigint;
      }
    ],
    "nonpayable"
  >;

  verifyDocumentView: TypedContractMethod<
    [_hash: string],
    [
      [bigint, string, bigint, bigint, string, string, bigint] & {
        status: bigint;
        issuedBy: string;
        issuedAt: bigint;
        revokedAt: bigint;
        ipfsCID: string;
        docType: string;
        verifyCount: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCertStatus"
  ): TypedContractMethod<[_hash: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVerifyCount"
  ): TypedContractMethod<[_hash: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantIssuer"
  ): TypedContractMethod<[_issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "issuers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "revokeDocument"
  ): TypedContractMethod<[_hash: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeIssuer"
  ): TypedContractMethod<[_issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "storeDocument"
  ): TypedContractMethod<
    [_hash: string, _ipfsCID: string, _docType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[_newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyDocument"
  ): TypedContractMethod<
    [_hash: string],
    [
      [bigint, string, bigint, bigint, string, string, bigint] & {
        status: bigint;
        issuedBy: string;
        issuedAt: bigint;
        revokedAt: bigint;
        ipfsCID: string;
        docType: string;
        verifyCount: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyDocumentView"
  ): TypedContractMethod<
    [_hash: string],
    [
      [bigint, string, bigint, bigint, string, string, bigint] & {
        status: bigint;
        issuedBy: string;
        issuedAt: bigint;
        revokedAt: bigint;
        ipfsCID: string;
        docType: string;
        verifyCount: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "DocumentRevoked"
  ): TypedContractEvent<
    DocumentRevokedEvent.InputTuple,
    DocumentRevokedEvent.OutputTuple,
    DocumentRevokedEvent.OutputObject
  >;
  getEvent(
    key: "DocumentStored"
  ): TypedContractEvent<
    DocumentStoredEvent.InputTuple,
    DocumentStoredEvent.OutputTuple,
    DocumentStoredEvent.OutputObject
  >;
  getEvent(
    key: "DocumentVerified"
  ): TypedContractEvent<
    DocumentVerifiedEvent.InputTuple,
    DocumentVerifiedEvent.OutputTuple,
    DocumentVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerGranted"
  ): TypedContractEvent<
    IssuerGrantedEvent.InputTuple,
    IssuerGrantedEvent.OutputTuple,
    IssuerGrantedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerRevoked"
  ): TypedContractEvent<
    IssuerRevokedEvent.InputTuple,
    IssuerRevokedEvent.OutputTuple,
    IssuerRevokedEvent.OutputObject
  >;

  filters: {
    "DocumentRevoked(string,address,uint256)": TypedContractEvent<
      DocumentRevokedEvent.InputTuple,
      DocumentRevokedEvent.OutputTuple,
      DocumentRevokedEvent.OutputObject
    >;
    DocumentRevoked: TypedContractEvent<
      DocumentRevokedEvent.InputTuple,
      DocumentRevokedEvent.OutputTuple,
      DocumentRevokedEvent.OutputObject
    >;

    "DocumentStored(string,address,string,string,uint256)": TypedContractEvent<
      DocumentStoredEvent.InputTuple,
      DocumentStoredEvent.OutputTuple,
      DocumentStoredEvent.OutputObject
    >;
    DocumentStored: TypedContractEvent<
      DocumentStoredEvent.InputTuple,
      DocumentStoredEvent.OutputTuple,
      DocumentStoredEvent.OutputObject
    >;

    "DocumentVerified(string,address,uint8,uint256)": TypedContractEvent<
      DocumentVerifiedEvent.InputTuple,
      DocumentVerifiedEvent.OutputTuple,
      DocumentVerifiedEvent.OutputObject
    >;
    DocumentVerified: TypedContractEvent<
      DocumentVerifiedEvent.InputTuple,
      DocumentVerifiedEvent.OutputTuple,
      DocumentVerifiedEvent.OutputObject
    >;

    "IssuerGranted(address,address)": TypedContractEvent<
      IssuerGrantedEvent.InputTuple,
      IssuerGrantedEvent.OutputTuple,
      IssuerGrantedEvent.OutputObject
    >;
    IssuerGranted: TypedContractEvent<
      IssuerGrantedEvent.InputTuple,
      IssuerGrantedEvent.OutputTuple,
      IssuerGrantedEvent.OutputObject
    >;

    "IssuerRevoked(address,address)": TypedContractEvent<
      IssuerRevokedEvent.InputTuple,
      IssuerRevokedEvent.OutputTuple,
      IssuerRevokedEvent.OutputObject
    >;
    IssuerRevoked: TypedContractEvent<
      IssuerRevokedEvent.InputTuple,
      IssuerRevokedEvent.OutputTuple,
      IssuerRevokedEvent.OutputObject
    >;
  };
}
