/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DocChainInterface extends Interface {
  getFunction(
    nameOrSignature: "documents" | "storeDocument" | "verifyDocument"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DocumentStored"): EventFragment;

  encodeFunctionData(functionFragment: "documents", values: [string]): string;
  encodeFunctionData(
    functionFragment: "storeDocument",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDocument",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "documents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "storeDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDocument",
    data: BytesLike
  ): Result;
}

export namespace DocumentStoredEvent {
  export type InputTuple = [
    hash: string,
    owner: AddressLike,
    ipfsCID: string,
    docType: string
  ];
  export type OutputTuple = [
    hash: string,
    owner: string,
    ipfsCID: string,
    docType: string
  ];
  export interface OutputObject {
    hash: string;
    owner: string;
    ipfsCID: string;
    docType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DocChain extends BaseContract {
  connect(runner?: ContractRunner | null): DocChain;
  waitForDeployment(): Promise<this>;

  interface: DocChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  documents: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, bigint] & {
        hash: string;
        ipfsCID: string;
        docType: string;
        owner: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  storeDocument: TypedContractMethod<
    [_hash: string, _ipfsCID: string, _docType: string],
    [void],
    "nonpayable"
  >;

  verifyDocument: TypedContractMethod<
    [_hash: string],
    [[boolean, string, bigint, string, string]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "documents"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, bigint] & {
        hash: string;
        ipfsCID: string;
        docType: string;
        owner: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "storeDocument"
  ): TypedContractMethod<
    [_hash: string, _ipfsCID: string, _docType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyDocument"
  ): TypedContractMethod<
    [_hash: string],
    [[boolean, string, bigint, string, string]],
    "view"
  >;

  getEvent(
    key: "DocumentStored"
  ): TypedContractEvent<
    DocumentStoredEvent.InputTuple,
    DocumentStoredEvent.OutputTuple,
    DocumentStoredEvent.OutputObject
  >;

  filters: {
    "DocumentStored(string,address,string,string)": TypedContractEvent<
      DocumentStoredEvent.InputTuple,
      DocumentStoredEvent.OutputTuple,
      DocumentStoredEvent.OutputObject
    >;
    DocumentStored: TypedContractEvent<
      DocumentStoredEvent.InputTuple,
      DocumentStoredEvent.OutputTuple,
      DocumentStoredEvent.OutputObject
    >;
  };
}
