/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DocChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "INSTITUTE_ROLE"
      | "STUDENT_ROLE"
      | "admin"
      | "assignStudentRole"
      | "getCertStatus"
      | "getRoleAdmin"
      | "getStudentDocuments"
      | "getUserRole"
      | "getVerifyCount"
      | "grantIssuer"
      | "grantRole"
      | "hasRole"
      | "instituteName"
      | "issueToStudent"
      | "issuers"
      | "registerInstitute"
      | "renounceRole"
      | "revokeDocument"
      | "revokeIssuer"
      | "revokeRole"
      | "storeDocument"
      | "studentDocuments"
      | "supportsInterface"
      | "transferAdmin"
      | "verifyDocument"
      | "verifyDocumentView"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DocumentRevoked"
      | "DocumentStored"
      | "DocumentVerified"
      | "IssuerGranted"
      | "IssuerRevoked"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INSTITUTE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STUDENT_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "assignStudentRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertStatus",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudentDocuments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifyCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "grantIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "instituteName",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueToStudent",
    values: [string, string, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issuers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerInstitute",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDocument",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storeDocument",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "studentDocuments",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDocument",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDocumentView",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INSTITUTE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STUDENT_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assignStudentRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStudentDocuments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerifyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "instituteName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueToStudent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "issuers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerInstitute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "storeDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "studentDocuments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDocumentView",
    data: BytesLike
  ): Result;
}

export namespace DocumentRevokedEvent {
  export type InputTuple = [
    hashKey: string,
    revokedBy: AddressLike,
    revokedAt: BigNumberish
  ];
  export type OutputTuple = [
    hashKey: string,
    revokedBy: string,
    revokedAt: bigint
  ];
  export interface OutputObject {
    hashKey: string;
    revokedBy: string;
    revokedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DocumentStoredEvent {
  export type InputTuple = [
    hashKey: string,
    issuedBy: AddressLike,
    ipfsCID: string,
    docType: string,
    issuedAt: BigNumberish
  ];
  export type OutputTuple = [
    hashKey: string,
    issuedBy: string,
    ipfsCID: string,
    docType: string,
    issuedAt: bigint
  ];
  export interface OutputObject {
    hashKey: string;
    issuedBy: string;
    ipfsCID: string;
    docType: string;
    issuedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DocumentVerifiedEvent {
  export type InputTuple = [
    hashKey: string,
    verifiedBy: AddressLike,
    status: BigNumberish,
    verifiedAt: BigNumberish
  ];
  export type OutputTuple = [
    hashKey: string,
    verifiedBy: string,
    status: bigint,
    verifiedAt: bigint
  ];
  export interface OutputObject {
    hashKey: string;
    verifiedBy: string;
    status: bigint;
    verifiedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerGrantedEvent {
  export type InputTuple = [issuer: AddressLike, grantedBy: AddressLike];
  export type OutputTuple = [issuer: string, grantedBy: string];
  export interface OutputObject {
    issuer: string;
    grantedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerRevokedEvent {
  export type InputTuple = [issuer: AddressLike, revokedBy: AddressLike];
  export type OutputTuple = [issuer: string, revokedBy: string];
  export interface OutputObject {
    issuer: string;
    revokedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DocChain extends BaseContract {
  connect(runner?: ContractRunner | null): DocChain;
  waitForDeployment(): Promise<this>;

  interface: DocChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  INSTITUTE_ROLE: TypedContractMethod<[], [string], "view">;

  STUDENT_ROLE: TypedContractMethod<[], [string], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  assignStudentRole: TypedContractMethod<
    [_student: AddressLike],
    [void],
    "nonpayable"
  >;

  getCertStatus: TypedContractMethod<[_hash: string], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getStudentDocuments: TypedContractMethod<
    [_student: AddressLike],
    [string[]],
    "view"
  >;

  getUserRole: TypedContractMethod<[_user: AddressLike], [string], "view">;

  getVerifyCount: TypedContractMethod<[_hash: string], [bigint], "view">;

  grantIssuer: TypedContractMethod<
    [_issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  instituteName: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  issueToStudent: TypedContractMethod<
    [_hash: string, _ipfsCID: string, _docType: string, _student: AddressLike],
    [void],
    "nonpayable"
  >;

  issuers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  registerInstitute: TypedContractMethod<
    [_institute: AddressLike, _name: string],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeDocument: TypedContractMethod<[_hash: string], [void], "nonpayable">;

  revokeIssuer: TypedContractMethod<
    [_issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  storeDocument: TypedContractMethod<
    [_hash: string, _ipfsCID: string, _docType: string],
    [void],
    "nonpayable"
  >;

  studentDocuments: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferAdmin: TypedContractMethod<
    [_newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyDocument: TypedContractMethod<
    [_hash: string],
    [
      [bigint, string, bigint, bigint, string, string, bigint] & {
        status: bigint;
        issuedBy: string;
        issuedAt: bigint;
        revokedAt: bigint;
        ipfsCID: string;
        docType: string;
        verifyCount: bigint;
      }
    ],
    "nonpayable"
  >;

  verifyDocumentView: TypedContractMethod<
    [_hash: string],
    [
      [bigint, string, bigint, bigint, string, string, bigint] & {
        status: bigint;
        issuedBy: string;
        issuedAt: bigint;
        revokedAt: bigint;
        ipfsCID: string;
        docType: string;
        verifyCount: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INSTITUTE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "STUDENT_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "assignStudentRole"
  ): TypedContractMethod<[_student: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCertStatus"
  ): TypedContractMethod<[_hash: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getStudentDocuments"
  ): TypedContractMethod<[_student: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getUserRole"
  ): TypedContractMethod<[_user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getVerifyCount"
  ): TypedContractMethod<[_hash: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantIssuer"
  ): TypedContractMethod<[_issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "instituteName"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "issueToStudent"
  ): TypedContractMethod<
    [_hash: string, _ipfsCID: string, _docType: string, _student: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "issuers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerInstitute"
  ): TypedContractMethod<
    [_institute: AddressLike, _name: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeDocument"
  ): TypedContractMethod<[_hash: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeIssuer"
  ): TypedContractMethod<[_issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "storeDocument"
  ): TypedContractMethod<
    [_hash: string, _ipfsCID: string, _docType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "studentDocuments"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[_newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyDocument"
  ): TypedContractMethod<
    [_hash: string],
    [
      [bigint, string, bigint, bigint, string, string, bigint] & {
        status: bigint;
        issuedBy: string;
        issuedAt: bigint;
        revokedAt: bigint;
        ipfsCID: string;
        docType: string;
        verifyCount: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyDocumentView"
  ): TypedContractMethod<
    [_hash: string],
    [
      [bigint, string, bigint, bigint, string, string, bigint] & {
        status: bigint;
        issuedBy: string;
        issuedAt: bigint;
        revokedAt: bigint;
        ipfsCID: string;
        docType: string;
        verifyCount: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "DocumentRevoked"
  ): TypedContractEvent<
    DocumentRevokedEvent.InputTuple,
    DocumentRevokedEvent.OutputTuple,
    DocumentRevokedEvent.OutputObject
  >;
  getEvent(
    key: "DocumentStored"
  ): TypedContractEvent<
    DocumentStoredEvent.InputTuple,
    DocumentStoredEvent.OutputTuple,
    DocumentStoredEvent.OutputObject
  >;
  getEvent(
    key: "DocumentVerified"
  ): TypedContractEvent<
    DocumentVerifiedEvent.InputTuple,
    DocumentVerifiedEvent.OutputTuple,
    DocumentVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerGranted"
  ): TypedContractEvent<
    IssuerGrantedEvent.InputTuple,
    IssuerGrantedEvent.OutputTuple,
    IssuerGrantedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerRevoked"
  ): TypedContractEvent<
    IssuerRevokedEvent.InputTuple,
    IssuerRevokedEvent.OutputTuple,
    IssuerRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "DocumentRevoked(string,address,uint256)": TypedContractEvent<
      DocumentRevokedEvent.InputTuple,
      DocumentRevokedEvent.OutputTuple,
      DocumentRevokedEvent.OutputObject
    >;
    DocumentRevoked: TypedContractEvent<
      DocumentRevokedEvent.InputTuple,
      DocumentRevokedEvent.OutputTuple,
      DocumentRevokedEvent.OutputObject
    >;

    "DocumentStored(string,address,string,string,uint256)": TypedContractEvent<
      DocumentStoredEvent.InputTuple,
      DocumentStoredEvent.OutputTuple,
      DocumentStoredEvent.OutputObject
    >;
    DocumentStored: TypedContractEvent<
      DocumentStoredEvent.InputTuple,
      DocumentStoredEvent.OutputTuple,
      DocumentStoredEvent.OutputObject
    >;

    "DocumentVerified(string,address,uint8,uint256)": TypedContractEvent<
      DocumentVerifiedEvent.InputTuple,
      DocumentVerifiedEvent.OutputTuple,
      DocumentVerifiedEvent.OutputObject
    >;
    DocumentVerified: TypedContractEvent<
      DocumentVerifiedEvent.InputTuple,
      DocumentVerifiedEvent.OutputTuple,
      DocumentVerifiedEvent.OutputObject
    >;

    "IssuerGranted(address,address)": TypedContractEvent<
      IssuerGrantedEvent.InputTuple,
      IssuerGrantedEvent.OutputTuple,
      IssuerGrantedEvent.OutputObject
    >;
    IssuerGranted: TypedContractEvent<
      IssuerGrantedEvent.InputTuple,
      IssuerGrantedEvent.OutputTuple,
      IssuerGrantedEvent.OutputObject
    >;

    "IssuerRevoked(address,address)": TypedContractEvent<
      IssuerRevokedEvent.InputTuple,
      IssuerRevokedEvent.OutputTuple,
      IssuerRevokedEvent.OutputObject
    >;
    IssuerRevoked: TypedContractEvent<
      IssuerRevokedEvent.InputTuple,
      IssuerRevokedEvent.OutputTuple,
      IssuerRevokedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
